name: .NET

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      ProjectName: NativeMessagingHost
      TargetPlatform: win-x64

    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3
    
    - name: Restore
      run: dotnet restore --runtime ${{ env.TargetPlatform }} --locked-mode --verbosity normal

    - name: Build
      run: dotnet build ${{ env.ProjectName }} --no-restore --runtime ${{ env.TargetPlatform }} --configuration Release --no-self-contained --verbosity normal

    - name: Publish
      run: dotnet publish ${{ env.ProjectName }} --no-build --configuration Release -p:PublishSingleFile=true --runtime ${{ env.TargetPlatform }} --no-self-contained
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ProjectName }}.exe
        path: ${{ env.ProjectName }}\bin\Release\net6.0-windows\publish\${{ env.TargetPlatform }}\*.exe
        if-no-files-found: error
